package de.iweinzierl.worktrack.analytics;

public enum AnalyticsEvents {

    ACTIVITY_RESUMED,
    ACTIVITY_PAUSED,

    GOOGLE_API_CONNECT_FAILURE,

    GEOFENCE_ENTER,
    GEOFENCE_ENTER_BUT_NO_WORKPLACE,
    GEOFENCE_EXIT,
    GEOFENCE_EXIT_IGNORE_AUTOMATED_EXIT,

    TRACKING_ITEM_SAVE,
    TRACKING_ITEM_SAVE_DUPLICATE,
    TRACKING_ITEM_SAVE_SUCCESS,
    TRACKING_ITEM_SAVE_FAILURE,
    TRACKING_ITEM_DELETE,
    TRACKING_ITEM_DELETE_SUCCESS,
    TRACKING_ITEM_DELETE_FAILURE,

    BACKUP_LOADING_FAILED,
    BACKUP_DELETION_FAILED,
    BACKUP_IMPORT_FAILED,
    BACKUP_JOB_EXECUTE,
    BACKUP_JOB_EXECUTE_FINISHED,
    BACKUP_JOB_EXECUTE_FAILURE,
    BACKUP_JOB_CANCELLED,
    BACKUP_JOB_SCHEDULED,
    BACKUP_JOB_SCHEDULE_FAILURE
}
